components:
  schemas:
    ValidationErrorModel:
      properties:
        ctx:
          anyOf:
          - type: object
          - type: 'null'
          description: an optional object which contains values required to render
            the error message.
          title: Error context
        loc:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          description: 'the error''s location as a list. '
          title: Location
        msg:
          anyOf:
          - type: string
          - type: 'null'
          description: a computer-readable identifier of the error type.
          title: Message
        type_:
          anyOf:
          - type: string
          - type: 'null'
          description: a human readable explanation of the error.
          title: Error Type
      title: ValidationErrorModel
      type: object
info:
  title: WorldGen-API
  version: 1.0.0
openapi: 3.1.0
paths:
  /:
    get:
      operationId: get_index
      responses: {}
  /api/world/{world_name}:
    get:
      description: '</br>Parameters:</br>    world_name (str): The name of the world
        to retrieve the data for.</br></br>Returns:</br>    dict: A JSON object containing
        the data of the specified world.</br></br>Raises:</br>    404: If the specified
        world does not exist.'
      operationId: get_api_world
      responses: {}
      summary: Retrieves the JSON data of a specific world by its name.
  /api/world/{world_name}/{category}:
    get:
      operationId: get_api_category
      responses: {}
  /world/{world_name}:
    get:
      operationId: get_world
      responses: {}
  /world/{world_name}/{category}:
    get:
      operationId: get_category
      responses: {}
